[package]
name = "detnetctl"
description = "A TSN/DetNet Node Controller with Interference Protection"
version = "0.1.0"
edition = "2021"
authors = ["Florian Kauer <florian.kauer@linutronix.de>"]

[features]
default = ["dbus", "bpf", "detd", "sysrepo"]
dbus = ["dep:dbus", "dep:dbus-crossroads", "dep:dbus-tokio", "dep:async-shutdown", "dep:async-trait"]
bpf = ["dep:libbpf-rs", "dep:libbpf-cargo", "dep:log", "dep:nix"]
detd = ["dep:bytes", "dep:prost"]
sysrepo = ["dep:sysrepo", "dep:yang2", "dep:ipnet"]
libbpf_with_sotoken = []

[dependencies]
anyhow = "1.0"
tokio = {version = "1.0", features=["rt", "net", "macros", "sync", "signal"]}
eui48 = "1.1.0"
getrandom = { version = "0.2.8", features = ["std"] }
env_logger = "0.10.0"

serde = { version = "1.0", features = ["derive"] }
serde_yaml = { version = "0.9" }

clap = { version = "4.2.0", features = ["derive","wrap_help","cargo"] }

futures = "0.3.11"

### dbus feature
# From github to include the set_sender feature just merged TODO replace when released
dbus = { git = "https://github.com/diwic/dbus-rs", branch = "master", optional = true }
dbus-crossroads = { git = "https://github.com/diwic/dbus-rs", branch = "master", optional = true }
dbus-tokio = { git = "https://github.com/diwic/dbus-rs", branch = "master", optional = true }

async-shutdown = { version = "0.1.2", optional = true }
async-trait = { version = "0.1.67", optional = true }

### bpf feature
libbpf-rs = { version = "0.19", optional = true }
log = { version = "0.4.17", optional = true }
nix = { version = "0.24", default-features = false, features = ["net", "user"], optional = true }

### detd feature
bytes = { version = "1.4.0", optional = true }
prost = { version = "0.11.6", optional = true }

### sysrepo feature
# sysrepo changes still need to be upstreamed
sysrepo = { git = "https://github.com/koalo/sysrepo-rs", branch = "poc/yang2-rs-integration", optional = true }
yang2 = { version = "0.5.1", optional = true }
ipnet = { version = "2.7.2", optional = true }

[build-dependencies]
### bpf feature
libbpf-cargo = { version = "0.13", optional = true }

### detd feature
prost-build = "0.11.6"

[dev-dependencies]
mockall = "0.11.3"
tokio-test = "0.4.2"
tempfile = "3.4.0"

