[package]
name = "detnetctl"
description = "A TSN/DetNet Node Controller with Interference Protection"
version = "0.1.0"
edition = "2021"
authors = ["Florian Kauer <florian.kauer@linutronix.de>"]

[dependencies]
anyhow = "1.0"
tokio = {version = "1.0", features=["rt", "net", "macros", "sync", "signal"]}
eui48 = "1.1.0"
getrandom = { version = "0.2.8", features = ["std"] }

serde = { version = "1.0", features = ["derive"] }
serde_yaml = { version = "0.9" }

clap = { version = "4.2.0", features = ["derive","wrap_help","cargo"] }

[dev-dependencies]
mockall = "0.11.3"
tokio-test = "0.4.2"
tempfile = "3.4.0"

