# SPDX-FileCopyrightText: 2023 Linutronix GmbH
# SPDX-License-Identifier: 0BSD

version: 0.7.0
bridged_apps:
  app0:
    vlans: [1]
    virtual_interface_app: veth0
    netns_app: app0
    virtual_interface_bridge: vethapp0
streams:
  stream_out_broadcast:
    incoming_interface: vethapp0
    identification:
      destination_address: ff:ff:ff:ff:ff:ff
      vid: 1
    outgoing_l2:
      - outgoing_interface: enp87s0
  stream_out_unicast:
    incoming_interface: vethapp0
    identification:
      destination_address: 02:00:00:00:00:02
      vid: 1
    outgoing_l2:
      - outgoing_interface: enp87s0
  stream_in_broadcast:
    incoming_interface: enp87s0
    identification:
      destination_address: ff:ff:ff:ff:ff:ff
      vid: 1
    outgoing_l2:
      - outgoing_interface: vethapp0
  stream_in_unicast:
    incoming_interface: enp87s0
    identification:
      destination_address: &myapp0mac 02:00:00:00:00:01
      vid: 1
    outgoing_l2:
      - outgoing_interface: vethapp0
interfaces:
  enp87s0:
    promiscuous: true
  veth0.1:
    ip_addresses: [[10.0.0.1,24]]
    mac_address: *myapp0mac
