# SPDX-FileCopyrightText: 2023 Linutronix GmbH
#
# SPDX-License-Identifier: 0BSD

apps:
  app0:
    logical_interface: enp1s0.3
    physical_interface: enp1s0
    period_ns: 100000
    offset_ns: 0
    size_bytes: 1000
    destination_address: cb:cb:cb:cb:cb:cb
    vid: 3
    pcp: 3
    ip_address: 10.0.52.2
    prefix_length: 32
  app1:
    logical_interface: eth1.2
    physical_interface: eth1
    period_ns: 200000
    offset_ns: 0
    size_bytes: 2000
    destination_address: ab:cb:cb:cb:cb:cb
    vid: 2
    pcp: 2
ptp:
  1:
    clock_class: 248
    clock_accuracy: 0x31
    offset_scaled_log_variance: 65535
    current_utc_offset: 37
    current_utc_offset_valid: true
    leap59: false
    leap61: false
    time_traceable: true
    frequency_traceable: false
    ptp_timescale: true
    time_source: 0xA0
    domain_number: 0
    gptp_profile: true
