# SPDX-FileCopyrightText: 2023 Linutronix GmbH
#
# SPDX-License-Identifier: 0BSD

version: 0.1.0
apps:
  app0:
    logical_interface: enp86s0.5
    physical_interface: enp86s0
    period_ns: 100000
    offset_ns: 0
    size_bytes: 1000
    destination_address: 48:21:0b:56:db:da
    vid: 5
    pcp: 3
    addresses: [[10.5.1.1, 24]]
    cgroup: /user.slice/
  app1:
    logical_interface: enp86s0.3
    physical_interface: enp86s0
    period_ns: 200000
    offset_ns: 0
    size_bytes: 2000
    destination_address: 48:21:0b:56:db:da
    vid: 3
    pcp: 2
ptp:
  active_instance: 1
  instances:
    1:
      clock_class: 248
      clock_accuracy: 0x31
      offset_scaled_log_variance: 65535
      current_utc_offset: 37
      current_utc_offset_valid: true
      leap59: false
      leap61: false
      time_traceable: true
      frequency_traceable: false
      ptp_timescale: true
      time_source: 0xA0
      gptp_profile: true
