app0:
  logical_interface: enp1s0.3
  physical_interface: enp1s0
  period_ns: 100000
  offset_ns: 0
  size_bytes: 1000
  destination_address: cb:cb:cb:cb:cb:cb
  vid: 3
  pcp: 3
  ip_address: 10.0.52.2
  prefix_length: 32
app1:
  logical_interface: eth1.2
  physical_interface: eth1
  period_ns: 200000
  offset_ns: 0
  size_bytes: 2000
  destination_address: ab:cb:cb:cb:cb:cb
  vid: 2
  pcp: 2
