# SPDX-FileCopyrightText: 2023 Linutronix GmbH
# SPDX-License-Identifier: 0BSD

name: Checks
on: [push]
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1.4.2
        with:
          packages: libelf-dev clang libdbus-1-dev protobuf-compiler gcc-multilib
      - name: Run clippy
        run: |
          # TODO for the moment do not use sysrepo feature, upstream packages are still too old
          cargo clippy --all-targets --no-default-features --features dbus,bpf,netlink,ptp --color=always -- -D warnings
  reuse:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1.4.2
        with:
          packages: reuse
      - name: Run reuse
        run: reuse lint

